/**
 * 自社分譲物件データ
 *
 * ── CSVフォーマット（yamato_subdivision_25.csv 準拠） ──
 * No, 物件名, 状態, 価格(万円), 土地面積(㎡), 土地面積(坪),
 * 路線, 最寄駅, 所在地(住所), 交通, 建ぺい率(%), 容積率(%)
 *
 * ── 写真 ──
 * public/images/bukken/web/_DSC70XX.jpg（全37枚・1200×675px）
 * 写真は複数物件で共有している施工事例写真のため、
 * エリアや物件特性に応じて割り当てています。
 * 実際の物件写真が揃い次第、photos配列を差し替えてください。
 */

export type BukkenStatus = "募集中" | "残りわずか" | "完売";

export type Bukken = {
  id: string;
  no: number;
  name: string;
  area: string;
  pref: string;
  address: string;
  line: string;
  station: string;
  stationAccess: string;
  landPrice: number | null;
  landM2: number;
  landTsubo: number;
  totalLots: number | null;
  remainingLots: number | null;
  status: BukkenStatus;
  coverageRatio: number;
  floorAreaRatio: number;
  concept: string;
  tags: string[];
  photos: string[];
};

/** 建物プライス（全物件共通） */
export const BUILD_PRICES = {
  kyo:  2180,
  hana: 2380,
} as const;

/** ── 物件一覧（CSV 25件完全版） ── */
export const BUKKEN_LIST: Bukken[] = [
  {
    id: "kyotanabe-tabayuta",
    no: 1,
    name: "京田辺市 田辺勇田",
    area: "京田辺市",
    pref: "京都府",
    address: "京都府京田辺市田辺勇田51-2",
    line: "近鉄京都線",
    station: "新田辺",
    stationAccess: "徒歩6分",
    landPrice: 1880,
    landM2: 110.00,
    landTsubo: 33.27,
    totalLots: 47,
    remainingLots: 12,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "奈良・大阪・京都の三方向へアクセス可能。通勤しながらも、緑豊かな京田辺で子育てしたいファミリーに。第3期最終販売。",
    tags: ["3方向アクセス", "駅徒歩6分", "47区画大型分譲地"],
    photos: [
      "/images/bukken/web/_DSC7008.jpg",
      "/images/bukken/web/_DSC7009.jpg",
    ],
  },
  {
    id: "ikoma-nakanabatake",
    no: 2,
    name: "生駒市 中菜畑２丁目",
    area: "生駒市",
    pref: "奈良県",
    address: "奈良県生駒市中菜畑２丁目",
    line: "近鉄生駒線",
    station: "菜畑",
    stationAccess: "徒歩9分",
    landPrice: 1780,
    landM2: 135.21,
    landTsubo: 40.90,
    totalLots: 23,
    remainingLots: 8,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "大阪難波まで約25分。40坪超の広い敷地で、子どもがのびのびと育つ家を。生駒の豊かな自然環境の中で。",
    tags: ["大阪通勤圏", "40坪超", "子育て環境◎"],
    photos: [
      "/images/bukken/web/_DSC7010.jpg",
      "/images/bukken/web/_DSC7011.jpg",
    ],
  },
  {
    id: "nara-hokkejicho",
    no: 3,
    name: "奈良市 法華寺町",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市法華寺町321-5",
    line: "近鉄難波・奈良線",
    station: "新大宮",
    stationAccess: "徒歩9分",
    landPrice: 2380,
    landM2: 177.01,
    landTsubo: 53.54,
    totalLots: 8,
    remainingLots: 3,
    status: "残りわずか",
    coverageRatio: 40,
    floorAreaRatio: 60,
    concept: "奈良の歴史的景観が広がる閑静な住宅地。53坪超の広大な敷地で、庭付きの豊かな暮らしを。残り3区画。",
    tags: ["53坪超", "閑静な住宅地", "残り3区画"],
    photos: [
      "/images/bukken/web/_DSC7012.jpg",
      "/images/bukken/web/_DSC7013.jpg",
    ],
  },
  {
    id: "ikoma-nishishirodai",
    no: 4,
    name: "生駒市 西白庭台２丁目",
    area: "生駒市",
    pref: "奈良県",
    address: "奈良県生駒市西白庭台２丁目20-5",
    line: "近鉄けいはんな線",
    station: "白庭台",
    stationAccess: "徒歩20分",
    landPrice: 2380,
    landM2: 173.34,
    landTsubo: 52.43,
    totalLots: 7,
    remainingLots: 5,
    status: "募集中",
    coverageRatio: 50,
    floorAreaRatio: 80,
    concept: "高台に広がる静かな住宅地。52坪超の広い敷地と眺望を活かした、ゆとりある暮らしを。",
    tags: ["高台・眺望良好", "52坪超", "閑静な環境"],
    photos: [
      "/images/bukken/web/_DSC7014.jpg",
      "/images/bukken/web/_DSC7015.jpg",
    ],
  },
  {
    id: "yamatokoriyama-yata",
    no: 5,
    name: "大和郡山市 矢田町",
    area: "大和郡山市",
    pref: "奈良県",
    address: "奈良県大和郡山市矢田町6393-2",
    line: "関西本線",
    station: "大和小泉",
    stationAccess: "徒歩26分",
    landPrice: 780,
    landM2: 130.00,
    landTsubo: 39.32,
    totalLots: 17,
    remainingLots: 9,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "やまと不動産の地元エリア。土地780万円から、建物込みでも2,960万円台（京シリーズ）。奈良でいちばんお得に家が建てられる場所のひとつ。",
    tags: ["土地780万円〜", "地元エリア", "コスパ最高"],
    photos: [
      "/images/bukken/web/_DSC7016.jpg",
      "/images/bukken/web/_DSC7017.jpg",
    ],
  },
  {
    id: "nara-nishitomigaoka",
    no: 6,
    name: "奈良市 西登美ヶ丘１丁目",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市西登美ヶ丘１丁目４－２１",
    line: "近鉄難波・奈良線",
    station: "学園前",
    stationAccess: "バス13分／停歩4分",
    landPrice: 2580,
    landM2: 264.39,
    landTsubo: 79.97,
    totalLots: 1,
    remainingLots: 1,
    status: "募集中",
    coverageRatio: 40,
    floorAreaRatio: 60,
    concept: "学園前エリアの高級住宅地。約80坪の広大な敷地で、唯一無二の邸宅を。奈良でもっとも豊かな住環境のひとつ。",
    tags: ["80坪の広大な敷地", "学園前エリア", "高級住宅地"],
    photos: [
      "/images/bukken/web/_DSC7018.jpg",
      "/images/bukken/web/_DSC7019.jpg",
    ],
  },
  {
    id: "tenri-maesai",
    no: 7,
    name: "天理市 前栽町",
    area: "天理市",
    pref: "奈良県",
    address: "奈良県天理市前栽町160",
    line: "近鉄天理線",
    station: "前栽",
    stationAccess: "徒歩7分",
    landPrice: 1380,
    landM2: 132.30,
    landTsubo: 40.02,
    totalLots: 17,
    remainingLots: 7,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "近鉄前栽駅から徒歩7分。40坪の広さを活かした自由設計の家を、静かで落ち着いた住環境の中で。",
    tags: ["駅徒歩7分", "40坪超", "閑静な住環境"],
    photos: [
      "/images/bukken/web/_DSC7020.jpg",
      "/images/bukken/web/_DSC7021.jpg",
    ],
  },
  {
    id: "ikaruga-koryu",
    no: 8,
    name: "斑鳩町 興留２丁目",
    area: "生駒郡斑鳩町",
    pref: "奈良県",
    address: "奈良県生駒郡斑鳩町興留２丁目2-23",
    line: "関西本線",
    station: "法隆寺",
    stationAccess: "徒歩10分",
    landPrice: 1580,
    landM2: 145.21,
    landTsubo: 43.92,
    totalLots: 8,
    remainingLots: 1,
    status: "残りわずか",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "法隆寺駅徒歩10分。第2期最終1区画。43坪の広さで自由設計の家を。この機会を逃すと次はありません。",
    tags: ["残り1区画", "法隆寺駅徒歩10分", "第2期最終"],
    photos: [
      "/images/bukken/web/_DSC7022.jpg",
      "/images/bukken/web/_DSC7023.jpg",
    ],
  },
  {
    id: "kizugawa-kabutodai",
    no: 9,
    name: "木津川市 兜台４丁目",
    area: "木津川市",
    pref: "京都府",
    address: "京都府木津川市兜台４丁目5-4",
    line: "近鉄京都線",
    station: "高の原",
    stationAccess: "徒歩12分",
    landPrice: null,
    landM2: 182.89,
    landTsubo: 55.32,
    totalLots: 2,
    remainingLots: 0,
    status: "完売",
    coverageRatio: 40,
    floorAreaRatio: 60,
    concept: "高の原エリアの55坪超の物件。完売いたしました。類似物件のご案内が可能です。",
    tags: ["55坪超", "高の原エリア", "完売"],
    photos: [
      "/images/bukken/web/_DSC7024.jpg",
    ],
  },
  {
    id: "nara-ukyo",
    no: 10,
    name: "奈良市 右京３丁目",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市右京３丁目12ー２",
    line: "近鉄京都線",
    station: "高の原",
    stationAccess: "徒歩15分",
    landPrice: 2880,
    landM2: 257.70,
    landTsubo: 77.95,
    totalLots: 1,
    remainingLots: 1,
    status: "募集中",
    coverageRatio: 40,
    floorAreaRatio: 60,
    concept: "高の原エリアの約78坪。奈良市内でも希少な広大な敷地。ゆとりある庭と駐車スペースを持つ家が実現できます。",
    tags: ["78坪の広大な敷地", "高の原エリア", "希少区画"],
    photos: [
      "/images/bukken/web/_DSC7025.jpg",
      "/images/bukken/web/_DSC7026.jpg",
    ],
  },
  {
    id: "kashihara-minamiyagi",
    no: 11,
    name: "橿原市 南八木町３丁目",
    area: "橿原市",
    pref: "奈良県",
    address: "奈良県橿原市南八木町３丁目234‐2",
    line: "桜井線",
    station: "畝傍",
    stationAccess: "徒歩7分",
    landPrice: 1980,
    landM2: 165.30,
    landTsubo: 50.00,
    totalLots: 3,
    remainingLots: 2,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "橿原神宮前から程近い、奈良盆地の中心部。50坪の敷地で、庭や駐車場にゆとりを持たせた暮らしが実現できます。",
    tags: ["50坪", "橿原エリア", "駅徒歩7分"],
    photos: [
      "/images/bukken/web/_DSC7027.jpg",
      "/images/bukken/web/_DSC7028.jpg",
    ],
  },
  {
    id: "kashihara-shijo",
    no: 12,
    name: "橿原市 四条町",
    area: "橿原市",
    pref: "奈良県",
    address: "奈良県橿原市四条町792ー6",
    line: "近鉄橿原線",
    station: "八木西口",
    stationAccess: "徒歩13分",
    landPrice: null,
    landM2: 132.32,
    landTsubo: 40.02,
    totalLots: 2,
    remainingLots: 0,
    status: "完売",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "橿原市四条町の全2区画。完売いたしました。類似物件のご案内が可能です。",
    tags: ["40坪超", "橿原エリア", "完売"],
    photos: [
      "/images/bukken/web/_DSC7029.jpg",
    ],
  },
  {
    id: "ikoma-koakecho",
    no: 13,
    name: "生駒市 小明町",
    area: "生駒市",
    pref: "奈良県",
    address: "奈良県生駒市小明町401-27",
    line: "近鉄難波・奈良線",
    station: "東生駒",
    stationAccess: "徒歩27分",
    landPrice: 2080,
    landM2: 166.62,
    landTsubo: 50.40,
    totalLots: 3,
    remainingLots: 2,
    status: "募集中",
    coverageRatio: 50,
    floorAreaRatio: 80,
    concept: "眺望最高の高台エリア。50坪超の広い敷地で、生駒の自然を毎日感じながら暮らせます。",
    tags: ["眺望最高", "50坪超", "高台"],
    photos: [
      "/images/bukken/web/_DSC7030.jpg",
      "/images/bukken/web/_DSC7031.jpg",
    ],
  },
  {
    id: "nara-shijodairo",
    no: 14,
    name: "奈良市 四条大路",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市四条大路３丁目2-58",
    line: "近鉄橿原線",
    station: "尼ヶ辻",
    stationAccess: "徒歩17分",
    landPrice: 2380,
    landM2: 172.88,
    landTsubo: 52.29,
    totalLots: 1,
    remainingLots: 1,
    status: "募集中",
    coverageRatio: 40,
    floorAreaRatio: 60,
    concept: "奈良市の中心部に近い52坪の物件。低容積率のゆとりある環境で、緑豊かな暮らしを。",
    tags: ["52坪", "奈良市内", "低容積率"],
    photos: [
      "/images/bukken/web/_DSC7032.jpg",
    ],
  },
  {
    id: "nara-ayameikenami",
    no: 15,
    name: "奈良市 あやめ池南６丁目",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市あやめ池南６丁目8-14",
    line: "近鉄難波・奈良線",
    station: "菖蒲池",
    stationAccess: "徒歩5分",
    landPrice: 1980,
    landM2: 131.00,
    landTsubo: 39.62,
    totalLots: 3,
    remainingLots: 2,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "菖蒲池駅から徒歩5分。奈良市内でも希少な駅近物件。通勤・通学に便利な立地で、家族全員が暮らしやすい。",
    tags: ["駅徒歩5分", "奈良市内", "駅近希少"],
    photos: [
      "/images/bukken/web/_DSC7033.jpg",
      "/images/bukken/web/_DSC7034.jpg",
    ],
  },
  {
    id: "nara-funabashicho",
    no: 16,
    name: "奈良市 船橋町",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市船橋町7-7",
    line: "近鉄難波・奈良線",
    station: "近鉄奈良",
    stationAccess: "徒歩11分",
    landPrice: 1980,
    landM2: 119.50,
    landTsubo: 36.14,
    totalLots: 3,
    remainingLots: 2,
    status: "募集中",
    coverageRatio: 80,
    floorAreaRatio: 400,
    concept: "近鉄奈良駅から徒歩11分。奈良の中心部に暮らしながら、大阪・京都へのアクセスも抜群。利便性と住みやすさを両立。",
    tags: ["近鉄奈良駅徒歩11分", "利便性◎", "奈良市中心部"],
    photos: [
      "/images/bukken/web/_DSC7036.jpg",
    ],
  },
  {
    id: "nara-horencho-1",
    no: 17,
    name: "奈良市 法蓮町（1区画）",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市法蓮町328-20",
    line: "近鉄難波・奈良線",
    station: "新大宮",
    stationAccess: "徒歩12分",
    landPrice: 1880,
    landM2: 191.81,
    landTsubo: 58.02,
    totalLots: 1,
    remainingLots: 1,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "奈良市法蓮町の58坪超。新大宮駅徒歩12分で、奈良市中心部へのアクセスも良好。広い敷地でゆったりと暮らせます。",
    tags: ["58坪超", "新大宮駅徒歩12分", "希少1区画"],
    photos: [
      "/images/bukken/web/_DSC7037.jpg",
      "/images/bukken/web/_DSC7038.jpg",
    ],
  },
  {
    id: "nara-horencho-2",
    no: 18,
    name: "奈良市 法蓮町（2区画）",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市法蓮町1206-3",
    line: "近鉄難波・奈良線",
    station: "近鉄奈良",
    stationAccess: "徒歩10分",
    landPrice: 1780,
    landM2: 145.44,
    landTsubo: 43.99,
    totalLots: 2,
    remainingLots: 2,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "近鉄奈良駅から徒歩10分。44坪の使いやすい敷地。大阪・京都へのアクセスが抜群で、共働き夫婦に人気のエリア。",
    tags: ["近鉄奈良駅徒歩10分", "共働き夫婦向け", "44坪"],
    photos: [
      "/images/bukken/web/_DSC7039.jpg",
      "/images/bukken/web/_DSC7040.jpg",
    ],
  },
  {
    id: "nara-suzakucho",
    no: 19,
    name: "奈良市 朱雀５丁目",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市朱雀５丁目15-19",
    line: "近鉄京都線",
    station: "高の原",
    stationAccess: "徒歩19分",
    landPrice: 2280,
    landM2: 206.40,
    landTsubo: 62.43,
    totalLots: 1,
    remainingLots: 1,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "高の原エリアの62坪超。学研都市線沿線で京都・大阪方面へのアクセスも良好。広い敷地でゆとりある暮らしを。",
    tags: ["62坪超", "高の原エリア", "希少1区画"],
    photos: [
      "/images/bukken/web/_DSC7041.jpg",
    ],
  },
  {
    id: "nara-shijodairo-1chome",
    no: 20,
    name: "奈良市 四条大路１丁目",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市四条大路１丁目15-25",
    line: "近鉄難波・奈良線",
    station: "新大宮",
    stationAccess: "徒歩19分",
    landPrice: null,
    landM2: 194.82,
    landTsubo: 58.93,
    totalLots: 1,
    remainingLots: 0,
    status: "完売",
    coverageRatio: 50,
    floorAreaRatio: 80,
    concept: "奈良市四条大路の約59坪。完売いたしました。類似物件のご案内が可能です。",
    tags: ["59坪", "新大宮エリア", "完売"],
    photos: [
      "/images/bukken/web/_DSC7042.jpg",
    ],
  },
  {
    id: "tawaramoto-yakuoji",
    no: 21,
    name: "磯城郡田原本町 薬王寺",
    area: "磯城郡田原本町",
    pref: "奈良県",
    address: "奈良県磯城郡田原本町大字藥王寺",
    line: "近鉄橿原線",
    station: "田原本",
    stationAccess: "徒歩10分",
    landPrice: 1180,
    landM2: 145.44,
    landTsubo: 43.99,
    totalLots: 4,
    remainingLots: 2,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "第4期最終販売。建物込み3,360万円台（京シリーズ）から新生活をスタートできます。奈良でもっとも土地が手に入りやすいエリアのひとつ。",
    tags: ["第4期最終", "建物込み3,360万〜", "田原本エリア"],
    photos: [
      "/images/bukken/web/_DSC7043.jpg",
    ],
  },
  {
    id: "ikaruga-horyuji",
    no: 22,
    name: "斑鳩町 法隆寺北２丁目",
    area: "生駒郡斑鳩町",
    pref: "奈良県",
    address: "奈良県生駒郡斑鳩町法隆寺北２丁目",
    line: "関西本線",
    station: "法隆寺",
    stationAccess: "徒歩21分",
    landPrice: 1180,
    landM2: 189.90,
    landTsubo: 57.44,
    totalLots: 8,
    remainingLots: 1,
    status: "残りわずか",
    coverageRatio: 40,
    floorAreaRatio: 80,
    concept: "法隆寺エリアの最終1区画。57坪超の広大な敷地で、低容積率ならではのゆとりある暮らしを。この機会をお見逃しなく。",
    tags: ["最終1区画", "57坪超", "法隆寺エリア"],
    photos: [
      "/images/bukken/web/_DSC7044.jpg",
    ],
  },
  {
    id: "nara-daianji",
    no: 23,
    name: "奈良市 大安寺２丁目",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市大安寺２丁目",
    line: "関西本線",
    station: "奈良",
    stationAccess: "徒歩27分",
    landPrice: 1680,
    landM2: 148.00,
    landTsubo: 44.77,
    totalLots: 2,
    remainingLots: 2,
    status: "募集中",
    coverageRatio: 60,
    floorAreaRatio: 200,
    concept: "JR奈良駅エリアの44坪。奈良市内の便利な立地で、土地1,680万円から。建物込み3,860万円台（京シリーズ）。",
    tags: ["JR奈良駅エリア", "建物込み3,860万〜", "44坪"],
    photos: [
      "/images/bukken/web/_DSC7008.jpg",
      "/images/bukken/web/_DSC7016.jpg",
    ],
  },
  {
    id: "nara-tomigaoka",
    no: 24,
    name: "奈良市 登美ヶ丘５丁目",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市登美ヶ丘５丁目3-10",
    line: "近鉄難波・奈良線",
    station: "学園前",
    stationAccess: "徒歩34分",
    landPrice: 2680,
    landM2: 294.08,
    landTsubo: 88.95,
    totalLots: 1,
    remainingLots: 1,
    status: "募集中",
    coverageRatio: 40,
    floorAreaRatio: 60,
    concept: "奈良最高の住宅地・登美ヶ丘エリア。約89坪の圧倒的な広さ。希少な1区画で、理想の邸宅を建てる最後のチャンス。",
    tags: ["89坪・圧倒的な広さ", "登美ヶ丘エリア", "希少1区画"],
    photos: [
      "/images/bukken/web/_DSC7010.jpg",
      "/images/bukken/web/_DSC7018.jpg",
    ],
  },
  {
    id: "nara-horencho-8",
    no: 25,
    name: "奈良市 法蓮町（8区画）",
    area: "奈良市",
    pref: "奈良県",
    address: "奈良県奈良市法蓮町",
    line: "近鉄難波・奈良線",
    station: "新大宮",
    stationAccess: "徒歩12分",
    landPrice: 2280,
    landM2: 169.70,
    landTsubo: 51.33,
    totalLots: 8,
    remainingLots: 6,
    status: "募集中",
    coverageRatio: 50,
    floorAreaRatio: 80,
    concept: "奈良市法蓮町の全8区画。新大宮駅徒歩12分で奈良市の中心部へのアクセスも良好。51坪のゆとりある敷地。",
    tags: ["新大宮駅徒歩12分", "51坪", "8区画の街"],
    photos: [
      "/images/bukken/web/_DSC7030.jpg",
      "/images/bukken/web/_DSC7033.jpg",
    ],
  },
];

/** ── ユーティリティ ── */

export function filterBukken(list: Bukken[], status?: BukkenStatus) {
  if (!status) return list;
  return list.filter((b) => b.status === status);
}

export function getAreas(list: Bukken[]) {
  return Array.from(new Set(list.map((b) => b.area)));
}

export function getActiveBukken(list: Bukken[]) {
  return list.filter((b) => b.status !== "完売");
}
